version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/ring_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GOOGLE_VISION_API_KEY=${GOOGLE_VISION_API_KEY:-5904f39a456b3d0de043c223a7bd53d1beff3964}
      - SESSION_TIMEOUT=3600
      - RECONNECT_TIMEOUT=30
      - FILTER_NUDITY_THRESHOLD=0.7
      - FILTER_VIOLENCE_THRESHOLD=0.8
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ring_db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb-data:
  redis-data:

networks:
  app-network:
    driver: bridge