spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ring_db
  redis:
    host: localhost
    port: 6379

server:
  port: 8080

google:
  vision:
    api:
      key: 5904f39a456b3d0de043c223a7bd53d1beff3964

ring:
  session:
    timeout: 3600  # Session timeout in seconds (1 hour)
    reconnect-timeout: 30  # Reconnect timeout in seconds
  filter:
    threshold:
      nudity: 0.7  # Threshold for nudity detection (0.0 to 1.0)
      violence: 0.8  # Threshold for violence detection (0.0 to 1.0)